---
platform: linux

image_resource:
  type: docker-image
  source: {repository: yeasy/hyperledger-fabric-sdk-node, tag: "latest"}

inputs:
  - name: git-dev
  - name: npm-repo-cache
outputs:
  - name: sonarqube-analysis-input

run:
  path: git-dev/ci/scripts/sonarqube-input.sh
