---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cathive/concourse-sonarqube-qualitygate-task
    tag: latest
inputs:
  - name: sonar-code-coverage
run:
  path: /sonarqube-qualitygate-check
  dir: sonar-code-coverage