---
jobs:
  - name: cache-modules
    plan:
      - get: git-dev
        trigger: true
      - get: npm-repo-cache
      - task: save-last-commit
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: alpine/git, tag: latest}
          inputs:
            - name: git-dev
          outputs:
            - name: keyvalout
          run:
            path: sh
            args:
              - -exc
              - |
                touch ./keyvalout/keyval.properties
                cd git-dev
                git reflog | grep HEAD@{1} | awk '{print "PASSED_COMMIT=""\x27"$1"\x27"}' > ../keyvalout/keyval.properties
                cat ../keyvalout/keyval.properties
      - put: keyval
        params:
          file: keyvalout/keyval.properties
  - name: test
    serial: true
    plan:
      - { get: keyval, passed: [cache-modules] }
      - { get: dev-branch, resource: git-dev, trigger: true, passed: [cache-modules] }
      - { get: node-cache, resource: npm-repo-cache, passed: [cache-modules] }
      - task: test
        file: dev-branch/ci/tasks/task-test.yml
      - task: package-sonar
        file: dev-branch/ci/tasks/task-sonar-package.yml
      - aggregate:
          - put: sonar-code-coverage-95
            params: &sonar-params
              project_key: "node-dev-code-coverage"
              project_name: node-concourse-demo-cc
              project_path: sonarqube-analysis-package
              sources: ["src", "app.js"]
              scanner_type: auto
              project_description: "Example node demo code coverage"
              project_version: 0.0.1
              branch_name: dev
              tests: ["tests"]
              additional_properties:
                sonar.language: js
                sonar.scm.provider: git
                sonar.javascript.lcov.reportPaths: coverage/lcov.info
          - put: sonar-code-quality-codesmell-2
            params:
              project_key: "node-dev-code-quality"
              project_name: node-concourse-demo-cq
              project_path: sonarqube-analysis-package
              sources: ["src", "app.js"]
              scanner_type: auto
              project_description: "Example node demo code coverage"
              project_version: 0.0.1
              branch_name: dev
              tests: ["tests"]
              additional_properties:
                sonar.language: js
                sonar.scm.provider: git
                sonar.javascript.lcov.reportPaths: coverage/lcov.info
          - put: sonar-code-coverage-75
            params:
              project_key: "node-dev-code-coverage-80"
              project_name: node-dev-code-coverage-80
              project_path: sonarqube-analysis-package
              sources: ["src", "app.js"]
              scanner_type: auto
              project_description: "Example node demo code coverage"
              project_version: 0.0.1
              branch_name: dev
              tests: ["tests"]
              additional_properties:
                sonar.language: js
                sonar.scm.provider: git
                sonar.javascript.lcov.reportPaths: coverage/lcov.info
          - put: sonar-code-quality-codesmell-1
            params:
              project_key: "node-dev-code-quality-zero"
              project_name: node-dev-code-quality-zero
              project_path: sonarqube-analysis-package
              sources: ["src", "app.js"]
              scanner_type: auto
              project_description: "Example node demo code coverage"
              project_version: 0.0.1
              branch_name: dev
              tests: ["tests"]
              additional_properties:
                sonar.language: js
                sonar.scm.provider: git
                sonar.javascript.lcov.reportPaths: coverage/lcov.info
  - name: "code-coverage-gate-95%"
    plan:
      - { get: sonar-code-coverage-95, trigger: true, passed: [test] }
      - task: check-sonarqube-code-coverage
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: cathive/concourse-sonarqube-qualitygate-task,tag: latest }
          inputs:
            - name: sonar-code-coverage-95
          run: { path: /sonarqube-qualitygate-check, dir: sonar-code-coverage-95 }
  - name: code-quality-gate-codesmell-2
    plan:
      - { get: sonar-code-quality-codesmell-2, trigger: true, passed: [test] }
      - task: check-sonarqube-code-quality
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: cathive/concourse-sonarqube-qualitygate-task, tag: latest }
          inputs:
            - name: sonar-code-quality-codesmell-2
          run: { path: /sonarqube-qualitygate-check, dir: sonar-code-quality-codesmell-2 }
  - name: "code-coverage-gate-75%"
    plan:
      - { get: sonar-code-coverage-75, trigger: true, passed: [test] }
      - task: check-sonarqube-code-coverage
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: cathive/concourse-sonarqube-qualitygate-task,tag: latest }
          inputs:
            - name: sonar-code-coverage-75
          run: { path: /sonarqube-qualitygate-check, dir: sonar-code-coverage-75 }
  - name: code-quality-gate-codesmell-1
    plan:
      - { get: sonar-code-quality-codesmell-1, trigger: true, passed: [test] }
      - task: check-sonarqube-code-quality
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: cathive/concourse-sonarqube-qualitygate-task, tag: latest }
          inputs:
            - name: sonar-code-quality-codesmell-1
          run: { path: /sonarqube-qualitygate-check, dir: sonar-code-quality-codesmell-1 }
  - name: merge-to-master
    plan:
      - { get: sonar-code-coverage-75, trigger: false, passed: ["code-coverage-gate-75%"] }
      - { get: sonar-code-quality-codesmell-2, trigger: false, passed: [code-quality-gate-codesmell-2] }
      - { get: sonar-code-coverage-95, trigger: false, passed: ["code-coverage-gate-95%"] }
      - { get: sonar-code-quality-codesmell-1, trigger: false, passed: [code-quality-gate-codesmell-1] }
      - task: check-sonarqube-code-quality-2
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: cathive/concourse-sonarqube-qualitygate-task, tag: latest }
          inputs:
            - name: sonar-code-quality-codesmell-2
          run: { path: /sonarqube-qualitygate-check, dir: sonar-code-quality }
      - task: check-sonarqube-code-coverage-95
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: cathive/concourse-sonarqube-qualitygate-task,tag: latest }
          inputs:
            - name: sonar-code-coverage-95
          run: { path: /sonarqube-qualitygate-check, dir: sonar-code-coverage }
      - task: check-sonarqube-code-quality-1
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: cathive/concourse-sonarqube-qualitygate-task, tag: latest }
          inputs:
            - name: sonar-code-quality-codesmell-1
          run: { path: /sonarqube-qualitygate-check, dir: sonar-code-quality }
      - task: check-sonarqube-code-coverage-75
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: cathive/concourse-sonarqube-qualitygate-task,tag: latest }
          inputs:
            - name: sonar-code-coverage-75
          run: { path: /sonarqube-qualitygate-check, dir: sonar-code-coverage }
      - { get: git-dev , trigger: false, passed: [test]}
      - { put: git-master, params: { repository: git-dev, merge: true } }

resource_types:
  - name: npm-cache
    type: docker-image
    source: {repository: ymedlop/npm-cache-resource, tag: "8"}
  - name: sonar-runner
    type: docker-image
    source: {repository: cathive/concourse-sonarqube-resource, tag: "0.8.1" }
  - name: keyval
    type: docker-image
    source:
      repository: swce/keyval-resource
resources:
  - name: keyval
    type: keyval
  - name: sonar-code-coverage-95
    type: sonar-runner
    source:
      host_url: "https://sonarcloud.io/"
      login: ((sonar-dev-cc))
      organization: huy-demo
  - name: sonar-code-quality-codesmell-2
    type: sonar-runner
    source:
      host_url: "https://sonarcloud.io/"
      login: ((sonar-dev-cq))
      organization: huy-demo
  - name: sonar-code-coverage-75
    type: sonar-runner
    source:
      host_url: "https://sonarcloud.io/"
      login: ((sonar-dev-cc-80))
      organization: huy-demo
  - name: sonar-code-quality-codesmell-1
    type: sonar-runner
    source:
      host_url: "https://sonarcloud.io/"
      login: ((sonar-dev-cq-zero))
      organization: huy-demo
  - name: git-master
    type: git
    source:
      branch: master
      uri: https://httran13:((github-token))@github.com/httran13/concourse-node.git
  - name: git-dev
    type: git
    source: &repo-source
      branch: dev
      uri: https://httran13:((github-token))@github.com/httran13/concourse-node.git
  - name: npm-repo-cache
    type: npm-cache
    source:
      yarn-support: true
      <<: *repo-source
      paths:
        - package.json